name: "Build"

on:
  workflow_call:
    inputs:
      MAVEN_SERVER_USERNAME:
        type: string
        default: ${{ github.actor }}
      java-version:
        type: string
        default: "17"
    secrets:
      MAVEN_SERVER_PASSWORD:
        required: false

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{inputs.java-version}}
          distribution: "temurin"

      - name: Maven Settings
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          servers: >
            [
              {
                "id": "github",
                "configuration": {
                  "httpHeaders": {
                    "property": {
                      "name": "Authorization",
                      "value": "${env.MAVEN_SERVER_TOKEN}"
                    }
                  }
                }
              }
            ]
          repositories: >
            [
              {
                "id": "github",
                "name": "commons-lib",
                "url": "https://maven.pkg.github.com/deelaa-marketplace/commons-lib",
                "releases": {
                  "enabled": "true",
                  "updatePolicy": "always"
                },
                "snapshots": {
                  "enabled": "true",
                  "updatePolicy": "always"
                }
              }
            ]

      - name: Print Maven Settings
        shell: bash
        run: cat /home/runner/.m2/settings.xml

      - name: Run Tests
        shell: bash
        run: mvn test
        env:
          MAVEN_SERVER_USERNAME: ${{ env.GITHUB_ACTOR }}
          MAVEN_SERVER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_SERVER_TOKEN: ${{ format('{0} {1}','Bearer', secrets.GITHUB_TOKEN) }}

      - name: Add Coverage Report
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Test Coverage Report"
          update-comment: true
          min-coverage-overall: 40
          min-coverage-changed-files: 85
