name: Manage Deployment

on:
  workflow_call:
    inputs:
      aws-region:
        type: string
        default: "eu-west-1"
      ecs-cluster:
        type: string
        required: true
      ecs-service:
        type: string
        required: false

env:
  AWS_REGION: ${{ inputs.aws-region }}
  ECS_SERVICE: ${{ inputs.ecs-service || github.event.repository.name }}
  ECS_CLUSTER: ${{ inputs.ecs-cluster }}

jobs:
  restart-deploy:
    name: Restart
    if: ${{ inputs.restart-deployment == 'false' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2.0.0

      - name: Force Deployment
        run: |
          aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE }} --force-new-deployment