name: Publish Artifacts

on:
  workflow_call:
    inputs:
      java-version:
        type: string
        default: "21"
      api-directory:
        type: string
        default: "src/main/resources/api-specification"
      messages-directory:
        type: string
        default: "src/main/resources/messages"
      distribution-repository:
        type: string
        default: "maven-central"

jobs:
  publish-artifact:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Determine Changes
        uses: dorny/paths-filter@v2.11.1
        id: changes
        with:
          filters: |
            api:
              - "${{ inputs.api-directory }}/**"
            messages:
              - "${{ inputs.messages-directory }}/**"

      - name: Setup Java
        uses: actions/setup-java@v4.0.0
        if: steps.changes.outputs.api == 'true' || steps.changes.outputs.messages == 'true'
        with:
          java-version: ${{inputs.java-version}}
          distribution: "temurin"
          cache: maven

      - name: Determine Artifact Details
        if: steps.changes.outputs.api == 'true' || steps.changes.outputs.messages == 'true'
        id: artifact
        shell: bash
        env:
          GITHUB_ACTOR: ${{ secrets.GIT_AGENT_USER }}
          GITHUB_TOKEN: ${{ secrets.GIT_AGENT_TOKEN }}
        run: |-
          echo "project_groupId=$(mvn help:evaluate -Dexpression=project.groupId -q -DforceStdout)" >> $GITHUB_OUTPUT 
          echo "project_artifactId=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_OUTPUT
          echo "project_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Bundle API
        if: steps.changes.outputs.api == 'true'
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: ${{ github.event.repository.name }}-api.zip
          directory: ${{ inputs.api-directory }}

      - name: Publish API
        if: steps.changes.outputs.api == 'true'
        shell: bash
        env:
          GITHUB_ACTOR: ${{ secrets.GIT_AGENT_USER }}
          GITHUB_TOKEN: ${{ secrets.GIT_AGENT_TOKEN }}
        run: >-
          mvn deploy:deploy-file 
          -DgroupId="${{ steps.artifact.outputs.project_groupId }}"
          -DartifactId="${{ steps.artifact.outputs.project_artifactId }}-api"
          -Dversion="${{ steps.artifact.outputs.project_version }}-${GITHUB_SHA:0:7}"
          -Dpackaging="zip"
          -Dfile="${{ github.workspace }}/${{ inputs.api-directory }}/${{ github.event.repository.name }}-api.zip"
          -DrepositoryId="github"
          -Durl="https://maven.pkg.github.com/${{ github.repository_owner }}/${{ inputs.distribution-repository }}"

      - name: Bundle Messages
        if: steps.changes.outputs.messages == 'true'
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: ${{ github.event.repository.name }}-messaging.zip
          directory: ${{ inputs.messages-directory }}

      - name: Publish Messages
        if: steps.changes.outputs.messages == 'true'
        shell: bash
        env:
          GITHUB_ACTOR: ${{ secrets.GIT_AGENT_USER }}
          GITHUB_TOKEN: ${{ secrets.GIT_AGENT_TOKEN }}
        run: >-
          mvn deploy:deploy-file 
          -DgroupId="${{ steps.artifact.outputs.project_groupId }}"
          -DartifactId="${{ steps.artifact.outputs.project_artifactId }}-messaging"
          -Dversion="${{ steps.artifact.outputs.project_version }}-${GITHUB_SHA:0:7}"
          -Dpackaging="zip"
          -Dfile="${{ github.workspace }}/${{ inputs.messages-directory }}/${{ github.event.repository.name }}-messaging.zip"
          -DrepositoryId="github"
          -Durl="https://maven.pkg.github.com/${{ github.repository_owner }}/${{ inputs.distribution-repository }}"
