name: Publish Messages Artifact

on:
  workflow_call:
    inputs:
      java-version:
        type: string
        default: "21"
      path:
        type: string
        default: "src/main/resources/messages/"
      distribution-repository:
        type: string
        default: "maven-central"

jobs:
  publish-messages:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Java
        uses: actions/setup-java@v4.0.0
        with:
          java-version: ${{inputs.java-version}}
          distribution: "temurin"
          cache: maven

      - name: Bundle Messages
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: ${{ github.event.repository.name }}-messaging.zip
          path: ${{ inputs.path }}

      - name: Determine Artifact Details
        id: artifact
        shell: bash
        env:
          GITHUB_ACTOR: ${{ secrets.GIT_AGENT_USER }}
          GITHUB_TOKEN: ${{ secrets.GIT_AGENT_TOKEN }}
        run: |-
          echo "project_groupId=$(mvn help:evaluate -Dexpression=project.groupId -q -DforceStdout)" >> $GITHUB_OUTPUT 
          echo "project_artifactId=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_OUTPUT
          echo "project_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Publish Messages
        shell: bash
        env:
          GITHUB_ACTOR: ${{ secrets.GIT_AGENT_USER }}
          GITHUB_TOKEN: ${{ secrets.GIT_AGENT_TOKEN }}
        run: >-
          mvn deploy:deploy-file 
          -DgroupId="${{ steps.artifact.outputs.project_groupId }}"
          -DartifactId="${{ steps.artifact.outputs.project_artifactId }}-messaging"
          -Dversion="${{ steps.artifact.outputs.project_version }}-${GITHUB_SHA:0:7}"
          -Dpackaging="zip"
          -Dfile="${{ github.workspace }}/${{ github.event.repository.name }}-messaging.zip"
          -DrepositoryId="github"
          -Durl="https://maven.pkg.github.com/${{ github.repository_owner }}/${{ inputs.distribution-repository }}"
