name: "Publish Package"

on:
  workflow_call:
    inputs:
      java-version:
        type: string
        default: "21"
      skip-snapshots:
        type: boolean
        default: true
      validate-version:
        type: boolean
        description: 'Validate that version input matches the version in pom.xml'
        default: true
      version:
        type: string
        description: 'Version: package version to publish other wise use the version in pom.xml'
        required: false

jobs:
  publish-package:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Java
        uses: actions/setup-java@v4.0.0
        with:
          java-version: ${{inputs.java-version}}
          distribution: "temurin"
          cache: maven

      - name: Print Maven Settings
        shell: bash
        run: cat /home/runner/.m2/settings.xml

      - name: Determine version
        id: version
        shell: bash
        env:
          GITHUB_ACTOR: ${{ secrets.GIT_AGENT_USER }}
          GITHUB_TOKEN: ${{ secrets.GIT_AGENT_TOKEN }}
        run: |-
          echo "package_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
          $(release_version=${{ inputs.version }} && echo "release_version=${release_version#v}" >> $GITHUB_OUTPUT)

      - name: Print version
        shell: bash
        run: |-
          echo "package_version=${{ steps.version.outputs.package_version }}" 
          echo "release_version=${{ steps.version.outputs.release_version }}" 

      - name: Publish
        if: ${{ steps.version.outputs.release_version == '' || ( inputs.validate-version  && steps.version.outputs.release_version == steps.version.outputs.package_version ) }}
        shell: bash
        env:
          GITHUB_ACTOR: ${{ secrets.GIT_AGENT_USER }}
          GITHUB_TOKEN: ${{ secrets.GIT_AGENT_TOKEN }}
        run: >-
          mvn --batch-mode -DskipTests 
          -Dmaven.deploy.skip=${{ inputs.skip-snapshots && 'snapshots' || 'false' }} 
          deploy